### ISSUE TITLE
Implement BitID.

### ISSUE THREAD

**Issue by ianpurton** [onchain/ionic-bitcoin-wallet#2]
Implement https://github.com/bitid/bitid

**Comment by MichaelKuhinica** [comment]
On step 2 of BitID BIP, the user is asked to select an address to use for sign in. 
AddressService on ionic-bitcoin-wallet only stores the last used address for each wallet on local storage (or am I missing something?). In this case, should I prompt the user to select a wallet to complete the authentication or automatically sign in with the current wallet address?

**Comment by ianpurton** [comment]
You can use the current wallet address. However you'll need to use the same address each time they log in. So if the user restores their wallet from a backup, can they continue to login to their sites ?

**Comment by MichaelKuhinica** [comment]
Ideally they can, since it's a HD wallet and the private key is the same but I will test it to make sure.
Since I will always use the current wallet to sign the authorisation message can I skip step 2 to have a better user experience?

**Comment by ianpurton** [comment]
Yes definitely. Want to make this as easy on the user as possible.
